export const SUCCESS = 'success'
export const ERROR   = 'error'
export const SERVIDOR_CORRIENDO  = 'Servidor corriendo en el puerto'
export const NOMBRE_REQUERIDO    = 'El nombre es un campo requerido'
export const PRODUCTO_REQUERIDO  = 'El producto es un campo requerido'
export const UNIDADES_REQUERIDO  = 'Las unidades es un campo requerido'
export const CLIENTE_REQUERIDO   = 'El cliente es un campo requerido'
export const PROVEEDOR_REQUERIDO = 'El proveedor es un campo requerido'
